// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Stats", {
  address: __t.string(),
  currentStreak: __t.f64(),
  highestStreak: __t.f64(),
  allTimeGmCount: __t.f64(),
  lastGmDay: __t.u256(),
  updatedAt: __t.timestamp(),
});


